############################
## CHANGE THESE
############################

baseURL: 'https://SizhuangHe.github.io/my_website'
title: my_website

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


