############################
## Navbar
############################

main:
- name: Home
  url: /
  weight: 10
- name: About Me
  url: /about/
  weight: 20
- name: News
  url: /news/
  weight: 30
# - name: Blogs
#   url: /blog/
#   weight: 40
